name: Deploy Bot to Ubuntu Server on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: ssh-keyscan -H 161.97.137.120 >> ~/.ssh/known_hosts

      - name: Ensure directory exists and sync files
        run: |
          ssh root@161.97.137.120 "mkdir -p /root/server/bot"
          rsync -avz ./ root@161.97.137.120:/root/server/bot

      - name: Install dependencies
        run: ssh root@161.97.137.120 "cd /root/server/bot && npm install"

      - name: Check and restart or start pm2 process
        run: |
          ssh root@161.97.137.120 << 'EOF'
            cd /root/server/bot
            if pm2 list | grep -q register; then
              npm run pm2:restart
            else
               npm run pm2
            fi
          EOF

    env:
      NODE_ENV: production
